window.world = window.world || {};
window.world.currentSceneName = "shader_wavecolor1";
window.world.scenes = window.world.scenes || {};
window.world.scenes = [
	{cname:'波动线测试1',ename:'shader_wavecolor1'},
	{cname:'地形自定义草皮测试',ename:'terrain_custom_grass'},
	{cname:'自定义Geometry测试',ename:'customgeo_grass'},
	{cname:'Shader测试1',ename:'material_shader1'},
	{cname:'Glsl文件测试1',ename:'material_shader2'},
	{cname:'人物模型控制',ename:'avatar'},
	{cname:'mmd人物模型控制',ename:'avatar_mmd'},
	{cname:'mmd动画',ename:'mmd'},
	{cname:'mmd半壶纱动画',ename:'mmd_bhs'},
	{cname:'角色动画',ename:'animation'},
	{cname:'地形颜色',ename:'terrainc'},
	{cname:'四面墙',ename:'fourwall'},
	{cname:'水植被',ename:'terrain_plant_water'},
	{cname:'高塔路',ename:'rollercoaster2'},
	{cname:'过山车',ename:'rollercoaster'},
	{cname:'击碎它',ename:'physic_body_break'},
	{cname:'物理布',ename:'physic_soft_cloth'},
	{cname:'软体球',ename:'physic_soft_mesh'},
	{cname:'绳子球',ename:'physic_soft_rope'},
	{cname:'弹簧关节',ename:'joint_spring_dof'},
	{cname:'车基本体',ename:'car_basic'},
	{cname:'摩托车体',ename:'moto_basic'},
	{cname:'开汽车',ename:'buggy'},
	{cname:'寻路者',ename:'findpath_flatsurface'},
	{cname:'地形寻路',ename:'findpath_terrain'},
	{cname:'静竹轩模型测试',ename:'data13'},
	{cname:'机房',ename:'datacenter_demo1'},
	{cname:'好多车',ename:'cars'},
	{cname:'塔',ename:'tower'},
	{cname:'绳子',ename:'softRope'},
	{cname:'射线',ename:'ray'},
	{cname:'组合体',ename:'compound'},
	{cname:'关节点对点',ename:'joint_p2p'},
	{cname:'迷宫',ename:'maze'},
	{cname:'街道',ename:'street'}];